#!/usr/bin/env python3

import cgi
import urllib.parse
import urllib.request
import base64
import json
import time
from http import cookies

form = cgi.FieldStorage()

refresh_token = form["refresh_token"].value

url = "https://www.reddit.com/api/v1/access_token"
values = {
    "grant_type": "refresh_token",
    "refresh_token": refresh_token
}

password_str = base64.b64encode(str.encode(open("../clientinfo").read()))

headers = {
    "Content-Type" : "application/x-www-form-urlencoded",
    "Authorization": "Basic " + str(password_str.decode("ascii")),
    "User-Agent": "RedditWall/0.1 by thedonkeypie"
}

data = urllib.parse.urlencode(values)
data = data.encode("utf-8")

req = urllib.request.Request(url, data, headers)

response = urllib.request.urlopen(req)

response_json = json.loads(response.read().decode("utf-8"))
access_token = response_json["access_token"]

forever_date = 315569260 #10 years

cookie = cookies.SimpleCookie()

cookie["access_token"] = access_token
cookie["access_token"]["expires"] = int(response_json["expires_in"])
cookie["access_token"]["path"] = "/"

cookie["authdate"] = int(time.time()) * 1000
cookie["authdate"]["expires"] = forever_date
cookie["authdate"]["path"] = "/"

print(str(cookie))
print("Content-Type: text/plain\n")
print("OK")
#print(response.read().decode("utf-8"))